title: Cliff-Lee
url: "https://sigurnna.github.io"
baseurl: "/home"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/home"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/승준-이-81b487147/"
 - name: "Support"
   link: "/home/support"
